package com.example.workflow.enums;

public enum SubType {
    CALL_BACK_AFTER_MISSED_INBOUND_CALL,
    CALL_AGAIN_AFTER_UNATTENDED_OUTBOUND_CALL,
    EMAIL_FOLLOW_UP_AFTER_SUCCESSFUL_CALL,
    EMAIL_AFTER_Y_UNATTENDED_OUTBOUND_CALL,
    REACT_TO_LAST_INTERACTION
}
