spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: admin

camunda.bpm.admin-user:
  id: demo
  password: demo

wkda:
  task:
    number:
      unattended:
        calls: 3
    target:
      minutes:
        CALL_BACK_AFTER_MISSED_INBOUND_CALL: 1
        CALL_AGAIN_AFTER_UNATTENDED_OUTBOUND_CALL: 1
        EMAIL_FOLLOW_UP_AFTER_SUCCESSFUL_CALL: 1
        EMAIL_AFTER_Y_UNATTENDED_OUTBOUND_CALL: 1
        REACT_TO_LAST_INTERACTION: 1